---
title: "Committee Meeting #2"
author: Isabella C. Richmond, PhD Candidate
date: May 5, 2023
format: 
  revealjs:
    theme: default
    incremental: false
    slide-number: c
    show-slide-number: all
---

## Structure

1.  What I've done this year
2.  What I am planning to do this upcoming year
3.  Discussion points

## Past year: academic

-   Presented at CSEE-ESA (Ch 1)
-   Ran a 4 month field season in Montréal (Ch 2)
    -   Mentored two undergraduates, one honours + one Mitacs intern
-   Completed data collection and cleaning for chapter 1
-   Switched projects for ch 3 + planned (planning) a field season
-   Did my first two peer reviews, with Carly

## Past year: side projects

-   Submitted two papers (BSc work)

-   Assisted Victoria Jepson (PhD, INRS) with field work, administering surveys in Ville Saint-Laurent

-   Started collaborating on a national project (UQAM/UBC/UofT/Concordia) to assess residents' perceptions of urban trees

    -   Using the data from this project to write a separate paper with Hiên's team and Carly

## Past year: teaching

-   Currently TAing with Carly as part of the "Infusing Black Scholarship" pilot program

-   Completed two guest lectures

-   Completed the Graduate Seminar in Teaching offered by CTL

## Past year: outreach

-   Regular Skype-a-Scientist meetings around the world

-   Delivered a tree identification workshop to Sinclar Laird Elementary School (Parc-Ex)

-   Did an interview with Carly for Radio-Canada on urban heat islands

-   Concordia's 4th space interview with Carly

## Past year: service

-   Graduate student mentor for the biology department

-   Graduate student representative for the Council of the School of Graduate Studies & Steering Committee

-   Graduate student representative for the Concordia Student Tribunal Pool

-   Graduate student representative for the Concordia Graduate Curriculum Committee

## Upcoming year

-   Poster presentation at CSEE (Ch 1)

-   Deploying temperature sensors for Ch 2 temperature data this summer

-   Executing a field season for Ch 3 with UdeM and UQAM teams in Montreal and Trois-Rivières

-   Submitting Ch 2 to a special issue this fall

-   & progress on all side projects and Ch 1 (of course!)

## Discussion: chapter 3
